# Generated by Django 4.0.3 on 2022-03-22 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphaCode', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('disorderType', models.CharField(max_length=100)),
                ('disorderGroup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpoID', models.CharField(max_length=100)),
                ('hpoTerm', models.CharField(max_length=100)),
                ('hpoFrequency', models.CharField(max_length=100)),
                ('disorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disorder')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
