# Generated by Django 4.0.3 on 2022-03-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_orphacode_disorder_orpha_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disorder',
            name='id',
        ),
        migrations.AlterField(
            model_name='disorder',
            name='orpha_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
