# Generated by Django 4.0.3 on 2022-03-23 01:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_disorder_id_alter_disorder_orpha_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder',
            name='symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, default=list, size=None),
        ),
    ]
