# Generated by Django 4.0.3 on 2022-03-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_disorder_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disorder',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
