# Generated by Django 3.2.6 on 2022-03-23 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='orpha_code',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='symptoms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2000), blank=True, default=list, size=None),
        ),
    ]
